export interface FieldSchema {
  id: string;
  label: string;
  type: 'text' | 'textarea' | 'number';
  placeholder?: string;
}

export interface DocumentSchema {
  id: string;
  name: string;
  party1Label: string;
  party2Label: string;
  defaultPartyStyle: 'both' | 'party1' | 'none';
  fields: FieldSchema[];
}

export const DOCUMENT_SCHEMAS: Record<string, DocumentSchema> = {
  'Legal Notice': {
    id: 'legal_notice',
    name: 'Legal Notice',
    party1Label: 'Client Details',
    party2Label: 'Opposite Party Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'documents_and_evidence', label: 'Documents and Evidence', type: 'textarea' },
      { id: 'cause_of_action', label: 'Cause of Action', type: 'textarea' },
      { id: 'applicable_legal_provisions', label: 'Applicable Legal Provisions', type: 'text' },
      { id: 'relief_demand_sought', label: 'Relief/Demand Sought', type: 'textarea' },
      { id: 'amount_involved', label: 'Amount Involved', type: 'text' },
      { id: 'time_limit_for_compliance', label: 'Time Limit for Compliance/Reply', type: 'text', placeholder: 'e.g., 15 Days' },
      { id: 'previous_communication_history', label: 'Previous Communication History', type: 'textarea' },
    ],
  },
  'Rent Agreement': {
    id: 'rent_agreement',
    name: 'Rent Agreement',
    party1Label: 'Landlord Details',
    party2Label: 'Tenant Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'property_details', label: 'Property Details', type: 'textarea' },
      { id: 'type_of_tenancy', label: 'Type of Tenancy (Residential/Commercial)', type: 'text' },
      { id: 'rent_amount', label: 'Rent Amount', type: 'text' },
      { id: 'security_deposit_details', label: 'Security Deposit Details', type: 'text' },
      { id: 'agreement_start_date', label: 'Agreement Start Date', type: 'text' },
      { id: 'agreement_duration', label: 'Agreement Duration (Lock-in Period, if any)', type: 'text' },
      { id: 'rent_payment_terms', label: 'Rent Payment Terms (Due Date, Mode of Payment)', type: 'text' },
      { id: 'maintenance_and_utility', label: 'Maintenance and Utility Charges Details', type: 'textarea' },
      { id: 'rent_increase_clause', label: 'Rent Increase Clause', type: 'text' },
      { id: 'permitted_use', label: 'Permitted Use of Property', type: 'textarea' },
      { id: 'restrictions_and_conditions', label: 'Restrictions and Conditions', type: 'textarea' },
      { id: 'notice_period', label: 'Notice Period for Termination', type: 'text' },
      { id: 'renewal_terms', label: 'Renewal Terms', type: 'textarea' },
      { id: 'possession_date', label: 'Possession Date', type: 'text' },
      { id: 'default_penalty_clause', label: 'Default and Penalty Clause', type: 'textarea' },
      { id: 'dispute_resolution', label: 'Dispute Resolution Clause', type: 'textarea' },
      { id: 'witness_details', label: 'Witness Details', type: 'textarea' },
      { id: 'additional_terms', label: 'Additional Terms and Conditions', type: 'textarea' },
    ],
  },
  'Affidavit': {
    id: 'affidavit',
    name: 'Affidavit',
    party1Label: 'Deponent Details (Affiant Details)',
    party2Label: 'N/A',
    defaultPartyStyle: 'none',
    fields: [
      { id: 'father_husband_name', label: "Father's/Husband's Name", type: 'text' },
      { id: 'age_of_deponent', label: 'Age of the Deponent', type: 'text' },
      { id: 'occupation_of_deponent', label: 'Occupation of the Deponent', type: 'text' },
      { id: 'residential_address', label: 'Residential Address', type: 'textarea' },
      { id: 'purpose_of_affidavit', label: 'Purpose/Subject of the Affidavit', type: 'text' },
      { id: 'facts_and_statements', label: 'Facts and Statements to be Declared', type: 'textarea' },
      { id: 'supporting_documents', label: 'Supporting Documents (if any)', type: 'textarea' },
      { id: 'verification_clause', label: 'Verification Clause', type: 'textarea' },
      { id: 'place_of_execution', label: 'Place of Execution', type: 'text' },
      { id: 'date_of_execution', label: 'Date of Execution', type: 'text' },
      { id: 'identification_details', label: 'Identification Details (if required)', type: 'text' },
      { id: 'witness_details', label: 'Witness Details (if required)', type: 'textarea' },
      { id: 'notary_details', label: 'Notary/Oath Commissioner Details and Attestation', type: 'textarea' },
    ],
  },
  'Demand Letter': {
    id: 'demand_letter',
    name: 'Demand Letter',
    party1Label: 'Sender/Client Details',
    party2Label: 'Recipient Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'subject', label: 'Subject of the Demand Letter', type: 'text' },
      { id: 'background_facts', label: 'Background Facts and Chronology of Events', type: 'textarea' },
      { id: 'nature_of_claim', label: 'Nature of the Claim/Dispute', type: 'textarea' },
      { id: 'amount_due', label: 'Amount or Obligation Due', type: 'text' },
      { id: 'supporting_documents', label: 'Supporting Documents and Evidence', type: 'textarea' },
      { id: 'previous_communications', label: 'Previous Communications (if any)', type: 'textarea' },
      { id: 'specific_demand', label: 'Specific Demand/Relief Sought', type: 'textarea' },
      { id: 'deadline_for_compliance', label: 'Deadline for Compliance/Response', type: 'text' },
      { id: 'consequences_of_noncompliance', label: 'Consequences of Non-Compliance', type: 'textarea' },
      { id: 'mode_of_payment', label: 'Mode of Payment/Performance (if applicable)', type: 'text' },
      { id: 'applicable_agreement', label: 'Applicable Agreement or Contract Details (if any)', type: 'textarea' },
      { id: 'place_and_date', label: 'Place and Date of the Letter', type: 'text' },
      { id: 'signature_authorization', label: 'Signature and Authorization Details', type: 'text' },
    ],
  },
  'Power of Attorney': {
    id: 'power_of_attorney',
    name: 'Power of Attorney',
    party1Label: 'Principal/Executant Details',
    party2Label: 'Attorney Holder (Agent) Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'relationship', label: 'Relationship Between Principal and Attorney Holder', type: 'text' },
      { id: 'type_of_poa', label: 'Type of Power of Attorney (General/Special)', type: 'text' },
      { id: 'purpose_of_poa', label: 'Purpose of the Power of Attorney', type: 'textarea' },
      { id: 'specific_powers', label: 'Specific Powers Granted', type: 'textarea' },
      { id: 'property_details', label: 'Property/Asset Details (if applicable)', type: 'textarea' },
      { id: 'restrictions', label: 'Restrictions or Limitations on Powers (if any)', type: 'textarea' },
      { id: 'effective_date', label: 'Effective Date', type: 'text' },
      { id: 'duration', label: 'Duration/Validity Period (if any)', type: 'text' },
      { id: 'revocation_clause', label: 'Revocation Clause', type: 'textarea' },
      { id: 'indemnity_clause', label: 'Indemnity Clause (if any)', type: 'textarea' },
      { id: 'governing_law', label: 'Governing Law and Jurisdiction', type: 'text' },
      { id: 'place_of_execution', label: 'Place of Execution', type: 'text' },
      { id: 'date_of_execution', label: 'Date of Execution', type: 'text' },
      { id: 'witness_details', label: 'Witness Details', type: 'textarea' },
      { id: 'notary_details', label: 'Notary/Registration Details (if applicable)', type: 'textarea' },
    ],
  },
  'Partnership Agreement': {
    id: 'partnership_agreement',
    name: 'Partnership Agreement',
    party1Label: 'Partner 1 Details',
    party2Label: 'Partner 2 Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'firm_details', label: 'Partnership Firm Details', type: 'textarea' },
      { id: 'name_and_business', label: 'Name and Business of the Firm', type: 'text' },
      { id: 'principal_place', label: 'Principal Place of Business', type: 'text' },
      { id: 'date_of_commencement', label: 'Date of Commencement of Partnership', type: 'text' },
      { id: 'nature_and_objectives', label: 'Nature and Objectives of Business', type: 'textarea' },
      { id: 'capital_contribution', label: 'Capital Contribution of Each Partner', type: 'textarea' },
      { id: 'profit_sharing_ratio', label: 'Profit and Loss Sharing Ratio', type: 'text' },
      { id: 'roles_and_duties', label: 'Roles, Duties, and Responsibilities of Partners', type: 'textarea' },
      { id: 'authority_and_powers', label: 'Authority and Powers of Partners', type: 'textarea' },
      { id: 'salary_and_drawings', label: 'Salary, Remuneration, and Drawings of Partners', type: 'textarea' },
      { id: 'banking_arrangements', label: 'Banking and Financial Arrangements', type: 'textarea' },
      { id: 'admission_of_partners', label: 'Admission of New Partners', type: 'textarea' },
      { id: 'retirement_and_death', label: 'Retirement, Resignation, or Death of a Partner', type: 'textarea' },
      { id: 'dissolution_clause', label: 'Dissolution of Partnership', type: 'textarea' },
      { id: 'accounts_and_audit', label: 'Accounts, Audit, and Record Maintenance', type: 'textarea' },
      { id: 'dispute_resolution', label: 'Dispute Resolution Clause', type: 'textarea' },
      { id: 'confidentiality_noncompete', label: 'Confidentiality and Non-Compete Clause', type: 'textarea' },
      { id: 'notice_requirements', label: 'Notice Requirements', type: 'textarea' },
      { id: 'governing_law', label: 'Governing Law and Jurisdiction', type: 'text' },
      { id: 'place_and_date', label: 'Place and Date of Execution', type: 'text' },
      { id: 'witness_details', label: 'Witness Details', type: 'textarea' },
    ],
  },
  'Employment Agreement': {
    id: 'employment_agreement',
    name: 'Employment Agreement',
    party1Label: 'Employer Details',
    party2Label: 'Employee Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'job_title', label: 'Job Title and Designation', type: 'text' },
      { id: 'job_description', label: 'Job Description and Responsibilities', type: 'textarea' },
      { id: 'date_of_joining', label: 'Date of Joining/Commencement Date', type: 'text' },
      { id: 'employment_type', label: 'Employment Type (Full-time/Part-time/Contract)', type: 'text' },
      { id: 'place_of_work', label: 'Place of Work', type: 'text' },
      { id: 'salary_details', label: 'Salary and Compensation Details', type: 'textarea' },
      { id: 'benefits_allowances', label: 'Benefits and Allowances', type: 'textarea' },
      { id: 'working_hours_leave', label: 'Working Hours and Leave Policy', type: 'textarea' },
      { id: 'probation_period', label: 'Probation Period Details', type: 'text' },
      { id: 'performance_evaluation', label: 'Performance Evaluation Terms', type: 'textarea' },
      { id: 'confidentiality', label: 'Confidentiality Clause', type: 'textarea' },
      { id: 'ip_rights', label: 'Intellectual Property Rights Clause', type: 'textarea' },
      { id: 'non_compete', label: 'Non-Compete and Non-Solicitation Clause', type: 'textarea' },
      { id: 'code_of_conduct', label: 'Code of Conduct and Company Policies', type: 'textarea' },
      { id: 'termination_notice', label: 'Termination and Notice Period', type: 'text' },
      { id: 'grounds_for_termination', label: 'Grounds for Termination', type: 'textarea' },
      { id: 'dispute_resolution', label: 'Dispute Resolution Clause', type: 'textarea' },
      { id: 'governing_law', label: 'Governing Law and Jurisdiction', type: 'text' },
      { id: 'place_and_date', label: 'Place and Date of Execution', type: 'text' },
      { id: 'witness_details', label: 'Witness Details', type: 'textarea' },
    ],
  },
  'Consumer Complaint': {
    id: 'consumer_complaint',
    name: 'Consumer Complaint',
    party1Label: 'Complainant Details',
    party2Label: 'Opposite Party Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'product_service_details', label: 'Product/Service Details', type: 'textarea' },
      { id: 'date_of_purchase', label: 'Date of Purchase/Transaction', type: 'text' },
      { id: 'invoice_details', label: 'Invoice/Bill/Order Details', type: 'text' },
      { id: 'defect_deficiency', label: 'Defect/Deficiency in Product or Service', type: 'textarea' },
      { id: 'facts_chronology', label: 'Facts and Chronology of Events', type: 'textarea' },
      { id: 'supporting_documents', label: 'Supporting Documents and Evidence', type: 'textarea' },
      { id: 'previous_communications', label: 'Previous Communications with Opposite Party', type: 'textarea' },
      { id: 'cause_of_action', label: 'Cause of Action', type: 'textarea' },
      { id: 'compensation_sought', label: 'Compensation/Relief Sought', type: 'textarea' },
      { id: 'amount_claimed', label: 'Amount Claimed', type: 'text' },
      { id: 'jurisdiction_details', label: 'Jurisdiction Details', type: 'text' },
      { id: 'delay_condonation', label: 'Delay Condonation Details (if applicable)', type: 'textarea' },
      { id: 'verification_declaration', label: 'Verification and Declaration', type: 'textarea' },
      { id: 'place_and_date', label: 'Place and Date of Filing', type: 'text' },
      { id: 'list_of_annexures', label: 'List of Annexures/Documents Attached', type: 'textarea' },
    ],
  },
  'Cheque Bounce Notice (NI Act Section 138)': {
    id: 'cheque_bounce',
    name: 'Cheque Bounce Notice (NI Act Section 138)',
    party1Label: 'Client/Payee Details',
    party2Label: 'Drawer (Cheque Issuer) Details',
    defaultPartyStyle: 'both',
    fields: [
      { id: 'cheque_details', label: 'Cheque Details (Number, Date, Bank Name, Amount)', type: 'textarea' },
      { id: 'date_of_presentation', label: 'Date of Presentation of Cheque', type: 'text' },
      { id: 'date_of_dishonour', label: 'Date of Dishonour of Cheque', type: 'text' },
      { id: 'reason_for_dishonour', label: 'Reason for Dishonour (as per Bank Memo)', type: 'text' },
      { id: 'bank_return_memo', label: 'Bank Return Memo Details', type: 'textarea' },
      { id: 'legally_enforceable_debt', label: 'Legally Enforceable Debt/Liability Details', type: 'textarea' },
      { id: 'facts_chronology', label: 'Facts and Chronology of Events', type: 'textarea' },
      { id: 'previous_communications', label: 'Previous Communications (if any)', type: 'textarea' },
      { id: 'demand_for_payment', label: 'Demand for Payment of Cheque Amount', type: 'text' },
      { id: 'amount_claimed', label: 'Amount Claimed', type: 'text' },
      { id: 'time_limit', label: 'Time Limit for Payment (15 Days from Receipt)', type: 'text', placeholder: '15 Days' },
      { id: 'consequences', label: 'Consequences of Non-Payment (NI Act Section 138)', type: 'textarea' },
      { id: 'supporting_documents', label: 'Supporting Documents and Evidence', type: 'textarea' },
      { id: 'place_and_date', label: 'Place and Date of the Notice', type: 'text' },
    ],
  },
  'Vakalatnama': {
    id: 'vakalatnama',
    name: 'Vakalatnama',
    party1Label: 'Client/Party Details',
    party2Label: 'Opposite Party Details',
    defaultPartyStyle: 'none',
    fields: [
      { id: 'case_court_details', label: 'Case/Court Details', type: 'textarea' },
      { id: 'advocate_firm_details', label: 'Advocate/Advocate Firm Details', type: 'textarea' },
      { id: 'nature_of_case', label: 'Nature of the Case/Proceeding', type: 'text' },
      { id: 'authority_granted', label: 'Authority Granted to the Advocate', type: 'textarea' },
      { id: 'court_tribunal_details', label: 'Court/Tribunal Details', type: 'text' },
      { id: 'case_number', label: 'Case Number (if already allotted)', type: 'text' },
      { id: 'place_of_execution', label: 'Place of Execution', type: 'text' },
      { id: 'date_of_execution', label: 'Date of Execution', type: 'text' },
      { id: 'witness_details', label: 'Witness Details (if required)', type: 'textarea' },
      { id: 'identification_details', label: 'Identification Details (if required)', type: 'textarea' },
      { id: 'advocate_enrollment', label: 'Advocate Enrollment Number and Bar Council Details', type: 'textarea' },
    ],
  },
};

export const DRAFT_TYPES = Object.keys(DOCUMENT_SCHEMAS);
