function escapeHtml(text) {
  return String(text)
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;');
}

function buildPdfFilename(formData) {
  const type = formData?.draftType?.replace(/\s+/g, '_') || 'legal_draft';
  return `${type}_${Date.now()}.pdf`;
}

function buildPdfDocument(draft, formData) {
  const draftType = formData?.draftType || 'Legal Draft';
  const dateStr = new Date().toLocaleDateString('en-IN', {
    day: 'numeric',
    month: 'long',
    year: 'numeric',
  });
  const party1 = formData?.party1Name || '';
  const party2 = formData?.party2Name || '';

  const root = document.createElement('div');
  root.className = 'draftee-pdf-root';

  const metaLines = [
    `<div><strong>Document:</strong> ${escapeHtml(draftType)}</div>`,
    `<div><strong>Date:</strong> ${escapeHtml(dateStr)}</div>`,
  ];
  if (party1) metaLines.push(`<div><strong>Party 1:</strong> ${escapeHtml(party1)}</div>`);
  if (party2) metaLines.push(`<div><strong>Party 2:</strong> ${escapeHtml(party2)}</div>`);

  root.innerHTML = `
    <link rel="preconnect" href="https://fonts.googleapis.com" />
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin />
    <link
      href="https://fonts.googleapis.com/css2?family=Noto+Serif+Devanagari:wght@400;600&family=Noto+Serif:ital,wght@0,400;0,600;1,400&family=Playfair+Display:wght@600&display=swap"
      rel="stylesheet"
    />
    <style>
      .draftee-pdf-root {
        width: 210mm;
        min-height: 297mm;
        box-sizing: border-box;
        padding: 18mm 20mm 22mm;
        background: #ffffff;
        color: #1a1a1a;
        font-family: 'Noto Serif', 'Noto Serif Devanagari', 'Times New Roman', Times, serif;
        font-size: 11pt;
        line-height: 1.55;
      }
      .draftee-pdf-header {
        border-bottom: 2px solid #c9a84c;
        padding-bottom: 10px;
        margin-bottom: 14px;
      }
      .draftee-pdf-brand {
        font-family: 'Playfair Display', 'Noto Serif', serif;
        font-size: 22pt;
        font-weight: 600;
        color: #8b7340;
        letter-spacing: 0.02em;
        margin: 0;
        line-height: 1.2;
      }
      .draftee-pdf-tagline {
        font-size: 9pt;
        color: #5c5c5c;
        margin: 4px 0 0;
        text-transform: uppercase;
        letter-spacing: 0.12em;
      }
      .draftee-pdf-meta {
        margin-top: 10px;
        font-size: 9.5pt;
        color: #444;
        display: grid;
        gap: 2px;
      }
      .draftee-pdf-meta strong {
        color: #1a1a1a;
        font-weight: 600;
      }
      .draftee-pdf-body {
        white-space: pre-wrap;
        word-wrap: break-word;
        text-align: justify;
        margin: 0;
        padding: 0;
      }
      .draftee-pdf-footer {
        margin-top: 20px;
        padding-top: 10px;
        border-top: 1px solid #ddd;
        font-size: 8pt;
        color: #777;
        text-align: center;
        font-style: italic;
      }
    </style>
    <header class="draftee-pdf-header">
      <h1 class="draftee-pdf-brand">Draftee</h1>
      <p class="draftee-pdf-tagline">Legal Draft Generator</p>
      <div class="draftee-pdf-meta">
        ${metaLines.join('')}
      </div>
    </header>
    <div class="draftee-pdf-body"></div>
    <footer class="draftee-pdf-footer">
      Generated by Draftee — For advocate review before filing or service.
    </footer>
  `;

  const bodyEl = root.querySelector('.draftee-pdf-body');
  if (bodyEl) {
    bodyEl.textContent = draft;
  }

  return root;
}

export async function downloadDraftPdf(draft, formData) {
  if (!draft?.trim()) return;

  const wrapper = document.createElement('div');
  wrapper.style.cssText =
    'position:fixed;left:-10000px;top:0;z-index:-1;pointer-events:none;';

  const doc = buildPdfDocument(draft, formData);
  wrapper.appendChild(doc);
  document.body.appendChild(wrapper);

  try {
    await document.fonts.ready;
    await new Promise((r) => setTimeout(r, 300));

    const html2pdf = (await import('html2pdf.js')).default;

    await html2pdf()
      .set({
        margin: [10, 10, 12, 10],
        filename: buildPdfFilename(formData),
        image: { type: 'jpeg', quality: 0.98 },
        html2canvas: {
          scale: 2,
          useCORS: true,
          logging: false,
          backgroundColor: '#ffffff',
        },
        jsPDF: { unit: 'mm', format: 'a4', orientation: 'portrait' },
        pagebreak: { mode: ['css', 'legacy'], avoid: '.draftee-pdf-header' },
      })
      .from(doc)
      .save();
  } finally {
    document.body.removeChild(wrapper);
  }
}
