export default function TermsContent() {
  return (
    <div className="space-y-6 text-cream/80 text-sm leading-relaxed">
      <div>
        <h1 className="text-2xl font-display text-gold mb-2">Terms and Conditions</h1>
        <p><strong>Draftee — AI Legal Draft Generator</strong></p>
        <p><strong>Effective Date:</strong> May 24, 2026</p>
        <p><strong>Last Updated:</strong> May 24, 2026</p>
      </div>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">1. Acceptance of Terms</h2>
        <p>By accessing or using Draftee (“the Platform”, “we”, “us”, or “our”) at draftee.in, you (“User”, “you”) agree to be bound by these Terms and Conditions. If you do not agree to these terms, please do not use the Platform.</p>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">2. About Draftee</h2>
        <p>Draftee is an AI-powered legal draft generation tool designed to assist Indian lawyers, advocates, and legal professionals in creating legal documents including notices, agreements, affidavits, and other legal drafts. Draftee is not a law firm and does not provide legal advice.</p>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">3. Not Legal Advice</h2>
        <p className="font-bold mb-2">IMPORTANT DISCLAIMER:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Draftee is a technology tool, not a law firm.</li>
          <li>The drafts generated by Draftee are <strong>AI-generated templates</strong> and do not constitute legal advice.</li>
          <li>All drafts must be reviewed and verified by a qualified, licensed advocate before use in any legal proceeding.</li>
          <li>Draftee does not guarantee the accuracy, completeness, or legal validity of any generated document.</li>
          <li>Use of Draftee does not create an attorney-client relationship.</li>
          <li>Draftee is not responsible for any legal consequences arising from the use of generated drafts without proper professional review.</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">4. Eligibility</h2>
        <p className="mb-2">To use Draftee, you must:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Be at least 18 years of age</li>
          <li>Be a registered advocate, lawyer, law student, or legal professional in India, or be using the platform under the supervision of a licensed advocate</li>
          <li>Provide accurate information when creating your account and profile</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">5. User Account</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>You are responsible for maintaining the confidentiality of your account credentials.</li>
          <li>You are responsible for all activities that occur under your account.</li>
          <li>You must notify us immediately at <a href="mailto:abhiksinha1523@gmail.com" className="text-gold hover:underline">abhiksinha1523@gmail.com</a> if you suspect any unauthorized use of your account.</li>
          <li>Draftee reserves the right to terminate accounts that violate these Terms.</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">6. Advocate Profile</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>Users must complete their Advocate Profile (including Advocate Name, Bar Council Number, and Court/Jurisdiction) to access full platform features including copying, downloading, and sharing drafts.</li>
          <li>By providing your Bar Council Number, you confirm that you are a registered legal professional or are operating under the supervision of one.</li>
          <li>Draftee does not independently verify Bar Council registrations.</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">7. Permitted Use</h2>
        <p className="mb-2">You may use Draftee to:</p>
        <ul className="list-disc pl-5 space-y-2 mb-4">
          <li>Generate AI-assisted legal drafts for professional legal use</li>
          <li>Save and manage your draft history</li>
          <li>Download and share drafts for legitimate legal purposes</li>
        </ul>
        <p className="mb-2">You may NOT use Draftee to:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Generate documents intended for fraudulent, illegal, or harmful purposes</li>
          <li>Harass, threaten, or defame any individual or organization</li>
          <li>Attempt to reverse-engineer, copy, or replicate the platform</li>
          <li>Resell or redistribute Draftee’s services without authorization</li>
          <li>Use automated scripts or bots to access the platform</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">8. Intellectual Property</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>All content, design, code, and technology on Draftee is owned by Draftee and protected under applicable Indian intellectual property laws.</li>
          <li>The drafts generated using your inputs are yours to use for legitimate legal purposes.</li>
          <li>You grant Draftee a non-exclusive license to process your inputs solely for the purpose of generating drafts.</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">9. AI-Generated Content Disclaimer</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>Draftee uses Google Gemini AI to generate legal drafts.</li>
          <li>AI-generated content may contain errors, outdated legal references, or inaccuracies.</li>
          <li>Indian laws including BNS (Bharatiya Nyaya Sanhita), BNSS (Bharatiya Nagarik Suraksha Sanhita), and BSA (Bharatiya Sakshya Adhiniyam) are evolving — always verify current applicable sections.</li>
          <li>Draftee expressly disclaims liability for any errors in AI-generated legal content.</li>
          <li><strong>Always verify all legal citations, sections, and case references with a qualified advocate before use.</strong></li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">10. Privacy and Data</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>Draftee collects your email, advocate profile details, and draft history to provide its services.</li>
          <li>We do not sell your personal data to third parties.</li>
          <li>Your draft content is stored securely via Supabase.</li>
          <li>By using Draftee, you consent to the collection and processing of your data as described above.</li>
          <li>For data deletion requests, contact: <a href="mailto:abhiksinha1523@gmail.com" className="text-gold hover:underline">abhiksinha1523@gmail.com</a></li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">11. Pricing and Payments</h2>
        <ul className="list-disc pl-5 space-y-2">
          <li>Draftee currently offers free access during its beta period.</li>
          <li>Premium features and pricing will be announced separately.</li>
          <li>All pricing will be in Indian Rupees (INR).</li>
          <li>Draftee reserves the right to modify pricing at any time with reasonable notice.</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">12. Limitation of Liability</h2>
        <p className="mb-2">To the maximum extent permitted by law:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Draftee shall not be liable for any direct, indirect, incidental, or consequential damages arising from your use of the platform.</li>
          <li>Draftee’s total liability in any matter shall not exceed the amount paid by you to Draftee in the preceding 3 months.</li>
          <li>Draftee is not liable for any loss arising from reliance on AI-generated drafts without proper legal review.</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">13. Indemnification</h2>
        <p className="mb-2">You agree to indemnify and hold harmless Draftee, its founders, employees, and partners from any claims, damages, or expenses arising from:</p>
        <ul className="list-disc pl-5 space-y-2">
          <li>Your use of the platform</li>
          <li>Your violation of these Terms</li>
          <li>Your use of AI-generated drafts without proper professional review</li>
        </ul>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">14. Modifications to Terms</h2>
        <p>Draftee reserves the right to modify these Terms at any time. Updated terms will be posted on the platform with a revised effective date. Continued use of the platform after changes constitutes acceptance of the new terms.</p>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">15. Governing Law and Jurisdiction</h2>
        <p>These Terms shall be governed by and construed in accordance with the laws of India. Any disputes arising from these Terms shall be subject to the exclusive jurisdiction of the courts in <strong>Silchar, Assam, India</strong>.</p>
      </section>

      <hr className="border-border" />

      <section>
        <h2 className="text-xl font-display text-gold mb-3">16. Contact Us</h2>
        <p className="mb-2">For any questions, concerns, or legal notices regarding these Terms, please contact:</p>
        <p><strong>Draftee</strong><br/>
        Email: <a href="mailto:abhiksinha1523@gmail.com" className="text-gold hover:underline">abhiksinha1523@gmail.com</a><br/>
        Website: draftee.in</p>
      </section>

      <hr className="border-border" />

      <p className="italic text-cream/50 pt-4">By using Draftee, you acknowledge that you have read, understood, and agree to these Terms and Conditions.</p>
    </div>
  );
}
